### ISSUE TITLE
Allow print_r(..., true)

### ISSUE THREAD

**Issue by samuelszabo** [spaze/phpstan-disallowed-calls#1]
Hello, would you mind to allow `print_r()` with `$return = true` argument?

We are using it quite often for a better format in logs.

I mean something like (`print_r()` specific):

```
services:
    -
        class: Spaze\PHPStan\Rules\Disallowed\FunctionCalls
        tags:
            - phpstan.rules.rule
        arguments:
            forbiddenCalls:
                -
                    function: 'print_r()'
                    allowReturn: true    #configurable
                    message: 'use logger instead'
```

https://github.com/spaze/phpstan-disallowed-calls/blob/master/src/FunctionCalls.php#L61 :
```php
 if ($name === $forbiddenCall['function']) {
                $returnArg = $node->args[1] ? $node->args[1]->value->name->__toString() === 'true' : false;
                if ($returnArg === true && $forbiddenCall['allowReturn']) {
                    return [];
                }
}
```

Thanks.

**Comment by spaze** [comment]
Hi, thanks. I'd love to allow some "forbidden calls" with specified parameters but I'd like it to be more generic and configurable.

For example `allowReturn` only makes sense with `print_r()` and `var_export()` but not with `var_dump()` for example.

What I do now, until support for params is added, I just simply ignore the error:
```
ignoreErrors:
	-
		message: '#^Calling print_r\(\) is forbidden, use logger instead#'  # Used with $return = true
		paths:
			- file.php
			- foo.php
```

To not have to ignore the error in many files, a logger that would accept any type and `print_r(..., true)`-it before actually logging it could also be used.

**Comment by spaze** [comment]
Thinking out loud here (may server as a note to self or to anyone willing to implement it) but something this is what I'd like to see:

The `allowedParams` here, with `type` and/or `value` keys (both may be extraneous, so maybe `type` or `value`, or maybe neither, optionally, would need to think about it a bit more):

```yaml
        arguments:
            forbiddenCalls:
                -
                    function: 'print_r()'
                    message: 'use logger instead'
                    allowedParams:
                      2:
                        type: boolean
                        value: true
```
