### ISSUE TITLE
error messages end with a dot

### ISSUE THREAD

**Issue by staabm** [spaze/phpstan-disallowed-calls#117]
in phpstan usually rule error messages end with a dot.

with a configuration like
```
    disallowedSuperglobals:
        -
            superglobal: '$_SESSION'
            message: 'use rex_request::session() and rex_request::setSession() instead for proper per instance scoping.'
```

it seems the extension is even trimming the configured dot.
