### ISSUE TITLE
Invalid configuration: Unexpected item 'parameters › disallowedFunctionCalls'.

### ISSUE THREAD

**Issue by k00ni** [spaze/phpstan-disallowed-calls#148]
I am calling PHPStan (v**1.9.2**, using **PHP 8.1.6**) with:
> vendor/bin/phpstan analyse -c phpstan.neon

and I get the following error when using one of your neon-files:
> Invalid configuration:
> Unexpected item 'parameters › disallowedFunctionCalls'.

My **PHPStan config** is:

```yaml
includes:
    - vendor/phpstan/phpstan-phpunit/extension.neon
    - vendor/phpstan/phpstan-strict-rules/rules.neon
    - vendor/spaze/phpstan-disallowed-calls/disallowed-dangerous-calls.neon
    # - vendor/phpstan/phpstan/conf/bleedingEdge.neon

parameters:
    bootstrapFiles:
        - vendor/autoload.php
    scanFiles:
      - config/bootstrap.php

    fileExtensions:
        - php

    level: 8

    paths:
        - src
        - test

    parallel:
        maximumNumberOfProcesses: 2

    tmpDir: ./var/cache/phpstan

    reportUnmatchedIgnoredErrors: true

    checkGenericClassInNonGenericObjectType: true

    ignoreErrors:
        - '/Variable method call on/'
        - '/Variable property access on DateInterval/'
        - '/Variable property access on App\\Service\\Statistics\\Class\\OrderPack/'
```

When only using `vendor/spaze/phpstan-disallowed-calls/extension.neon` it doesn't report anything (tested it with a blunt `var_dump`).

I would like to check out your PHPStan rules, but can't get it to work. Help is appreciated.
