### ISSUE TITLE
disallowedMethodCalls should also be triggered on inherited classes

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [spaze/phpstan-disallowed-calls#208]
i'd like to be strict in my codebase about doctrines magic methods.
given this configuration:

```yaml
  disallowedMethodCalls:
    -
      method: 'Doctrine\ORM\EntityRepository::find*()'
      message: 'to not use magic find*() methods'
      errorTip: 'add method to interface instead!'
      allowIn:
        - src/Repository/*
        - tests/*
```

i'd like to get all calls to `FooRepository::findOneBy()`
is there a way to disallow all calls to every child of EntityRepository?

also if a repository will implements the actual method, it would be nice to _not_ to trigger the error.

```php
class FooRepository extends EntityRepository {
   public function findBySpecificThing() {
   }
}

$repo = new FooRepository();
// this should not trigger an error upon calling
$repo->findBySpecificThing();
// this should trigger an error
$repo->findBy([ ... ]);

```
