### ISSUE TITLE
Unexpected item 'parameters › disallowedFunctionCalls'.

### ISSUE THREAD

**Issue by welly** [spaze/phpstan-disallowed-calls#264]
I'm running phpstan with phpstan-disallowed-calls in a bitbucket pipeline but getting the error in the title. Output from the pipeline looks like this:

```
+ php ./vendor/bin/phpstan analyse --memory-limit 1G
Note: Using configuration file /opt/atlassian/pipelines/agent/build/phpstan.neon.
Invalid configuration:
Unexpected item 'parameters › disallowedFunctionCalls'.
Invalid configuration:
Unexpected item 'parameters › disallowedMethodCalls'.

```

My phpstan.neon looks like:

```
parameters:
  customRulesetUsed: true
  reportUnmatchedIgnoredErrors: false
  paths:
    - drush
    - scripts
    - src

includes:
  - vendor/spaze/phpstan-disallowed-calls/disallowed-dangerous-calls.neon
  - vendor/spaze/phpstan-disallowed-calls/disallowed-execution-calls.neon
  - vendor/spaze/phpstan-disallowed-calls/disallowed-insecure-calls.neon
```

I've got phpstan/extension-installer installed. If I run

` ./vendor/bin/phpstan analyze --memory-limit 2048M src/modules/custom` in my local environment, it works as expected.

Any ideas what might be causing this?

Many thanks!
