### ISSUE TITLE
disallowedConstants resolve to actual value, making the rule useless

### ISSUE THREAD

**Issue by ruudk** [spaze/phpstan-disallowed-calls#48]
When using this configuration:
```neon
disallowedConstants:
        -
            constant: "DATE_ISO8601"
            message: 'use DATE_ATOM instead'
        -
            constant: "DateTime::ISO8601"
            message: 'use DateTimeInterface::ATOM instead'
        -
            constant: "DateTimeInterface::ISO8601"
            message: 'use DateTimeInterface::ATOM instead'
        -
            constant: "DateTimeImmutable::ISO8601"
            message: 'use DateTimeImmutable::ATOM instead'
```

I noticed that PHPStan resolves all the constants (except the first) to the actual value.

This makes the check useless as it will now compare `DateTimeImmutable::ISO8601` against `Y-m-d\TH:i:sO`.

I dumped `DisallowedHelper::createConstantsFromConfig` and saw this:
```
^ array:4 [
  0 => array:2 [
    "constant" => "DATE_ISO8601"
    "message" => "use DATE_ATOM instead"
  ]
  1 => array:2 [
    "constant" => "Y-m-d\TH:i:sO"
    "message" => "use DateTimeInterface::ATOM instead"
  ]
  2 => array:2 [
    "constant" => "Y-m-d\TH:i:sO"
    "message" => "use DateTimeInterface::ATOM instead"
  ]
  3 => array:2 [
    "constant" => "Y-m-d\TH:i:sO"
    "message" => "use DateTimeImmutable::ATOM instead"
  ]
]
```

**Comment by ruudk** [comment]
I think the problem is that there are no tests that load from neon.

**Comment by spaze** [comment]
Nice catch, thanks! I totally forgot that Nette Dependency Injection library used by PHPStan resolves constants to their actual value:

https://github.com/nette/di/blob/3d0aa5eb4479009c4ef25fcbe6457387b1d0df5a/src/DI/Helpers.php#L129-L135

when used as service parameters, which is done here:

https://github.com/spaze/phpstan-disallowed-calls/blob/d374688723748e213345932fdb77402e96eefcc0/extension.neon#L74

So unless I'd want to use the NEON parser directly to parse a file passed as a param to the `ClassConstantUsages` service, which I'd rather avoid, I could split the `constant: Foo::BAR` param to `class: Foo`, `constant: BAR` and join those manually which seems like the best option given the circumstances.

**Comment by spaze** [comment]
I've released the fix right away as [v1.2.2](https://github.com/spaze/phpstan-disallowed-calls/releases/tag/v1.2.2). Thanks again!

**Comment by ruudk** [comment]
@spaze Thanks for the lighting fast fix on this ⚡  I just tested it and it works as expected.

```
    disallowedConstants:
        -
            constant: 'DATE_ISO8601'
            message: 'use DATE_ATOM instead'
        -
            class: 'DateTime'
            constant: 'ISO8601'
            message: 'use DateTimeInterface::ATOM instead'
        -
            class: 'DateTimeInterface'
            constant: 'ISO8601'
            message: 'use DateTimeInterface::ATOM instead'
        -
            class: 'DateTimeImmutable'
            constant: 'ISO8601'
            message: 'use DateTimeImmutable::ATOM instead'
```

❤️
