### ISSUE TITLE
`allowCount` should be scoped to FQCN

### ISSUE THREAD

**Issue by spaze** [spaze/phpstan-disallowed-calls#89]
I made a small error in my thinking while working on this PR. 

This works fine:
```neon
parameters:
    disallowedMethodCalls:
        -
            method: 'Generated\MyNamedQuery::execute*()'
            message: 'do not reuse GraphQL queries.'
            allowCount: 1
```

It will only allow one call to `Generated\MyNamedQuery::execute*`.

But I want to go to a situation where I have 1 rule generic rule
```
parameters:
    disallowedMethodCalls:
        -
            method: 'Generated\*Query::execute*()'
            message: 'do not reuse GraphQL queries.'
            allowCount: 1
```
and it should track it's usages by FQCN instead of by rule. 

For example, I have 2 generated classes:
* `Generated\MyNamedQuery`
* `Generated\MyOtherQuery`

`MyNamedQuery::execute()` should be allowed to called once, and `MyOtherQuery::execute()` should be allowed to call once.

With the current setup, it tracks its usage on the rule and therefore blocks the second call to a separate class.

_Originally posted by @ruudk in https://github.com/spaze/phpstan-disallowed-calls/issues/87#issuecomment-952031965_
